"""Add created_by to activity_codes, machines, work_orders

Revision ID: 40af46fbbb08
Revises: 70ac29ed4801
Create Date: 2025-12-15 10:10:23.050168

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '40af46fbbb08'
down_revision = '70ac29ed4801'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_codes', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'activity_codes', 'employees', ['created_by'], ['id'])
    op.add_column('machines', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'machines', 'employees', ['created_by'], ['id'])
    op.add_column('work_orders', sa.Column('created_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'work_orders', 'employees', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'work_orders', type_='foreignkey')
    op.drop_column('work_orders', 'created_by')
    op.drop_constraint(None, 'machines', type_='foreignkey')
    op.drop_column('machines', 'created_by')
    op.drop_constraint(None, 'activity_codes', type_='foreignkey')
    op.drop_column('activity_codes', 'created_by')
    # ### end Alembic commands ###
