"""add manual machine/work_order text to job_cards

Revision ID: 43367d244435
Revises: 61f813de380d
Create Date: 2025-11-21 12:30:23.065004

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '43367d244435'
down_revision = '61f813de380d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_cards', sa.Column('manual_machine_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('job_cards', sa.Column('manual_work_order_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_cards', 'manual_work_order_text')
    op.drop_column('job_cards', 'manual_machine_text')
    # ### end Alembic commands ###
