"""add_shift_column

Revision ID: 5c5c9757c280
Revises: 3289ba2b8ec1
Create Date: 2025-11-12 23:45:12.642761

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5c5c9757c280'
down_revision = '3289ba2b8ec1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_cards', sa.Column('shift', sa.Integer(), nullable=True))
    op.alter_column('job_cards', 'approval_status',
               existing_type=postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='approvalstatusenum'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('job_cards', 'supervisor_remarks',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_cards', 'supervisor_remarks',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('job_cards', 'approval_status',
               existing_type=postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', name='approvalstatusenum'),
               server_default=sa.text("'PENDING'::approvalstatusenum"),
               existing_nullable=False)
    op.drop_column('job_cards', 'shift')
    # ### end Alembic commands ###
