"""Add created_by field to employees table

Revision ID: 70ac29ed4801
Revises: e42ce05285d1
Create Date: 2025-12-13 22:19:44.630387

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '70ac29ed4801'
down_revision = 'e42ce05285d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('created_by', sa.Integer(), nullable=True))
    # First update any existing values to be compatible with the enum
    op.execute("UPDATE employees SET supervisor_efficiency_module = NULL WHERE supervisor_efficiency_module NOT IN ('TIME_BASED', 'QUANTITY_BASED', 'TASK_BASED')")
    # Then alter the column type with explicit cast
    op.alter_column('employees', 'supervisor_efficiency_module',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('TIME_BASED', 'QUANTITY_BASED', 'TASK_BASED', name='efficiencytypeenum'),
               existing_nullable=True,
               postgresql_using='supervisor_efficiency_module::efficiencytypeenum')
    op.create_foreign_key(None, 'employees', 'employees', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.alter_column('employees', 'supervisor_efficiency_module',
               existing_type=sa.Enum('TIME_BASED', 'QUANTITY_BASED', 'TASK_BASED', name='efficiencytypeenum'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_column('employees', 'created_by')
    # ### end Alembic commands ###
