"""allow nullable machine_id/work_order_id

Revision ID: e42ce05285d1
Revises: 43367d244435
Create Date: 2025-11-21 15:49:58.783815

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'e42ce05285d1'
down_revision = '43367d244435'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_cards', 'machine_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('job_cards', 'work_order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('job_cards', 'work_order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('job_cards', 'machine_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
